// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmhnmxuveqcqilxhpbdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtaG5teHV2ZXFjcWlseGhwYmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODIwOTUsImV4cCI6MjA3MzM1ODA5NX0.XYHnU-p8p4oZGrIgawY7nwxdnkMEmtW0vOE8tTzoxT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});